label = {
    "category": [
        "CHAT",
        "EMAIL",
        "FILE_TRANSFER",
        "P2P",
        "STREAMING",
        "VOIP",
    ],
    "application": [
        "FACEBOOK_CHAT",
        "HANGOUT_CHAT",
        "ICQ_CHAT",
        "AIM_CHAT",
        "SKYPE_CHAT",
        "EMAIL_MAIL",
        "GMAIL_MAIL",
        "SKYPE_FTP",
        "SCP_FTP",
        "SFTP_FTP",
        "FTP_FTP",
        "YOUTUBE_STREAMING",
        "NETFLIX_STREAMING",
        "SPOTIFY_STREAMING",
        "VIMEO_STREAMING",
        "BITTORENT_P2P",
        "HANGOUT_VOIP",
        "SKYPE_VOIP",
        "FACEBOOK_VOIP",
        "VOIPBUSTER_VOIP",
    ],
}
